### ISSUE TITLE
Update to allow Magento 2.1 install

### ISSUE THREAD

**Issue by ajcollett** [PayFast/mod-magento_2#1]
This module currently does not work with magento 2.1, though I think it can. Simply add the composer file!

I have done this and it seems to be working, but I cannot confirm.

**Comment by Brendon-P** [comment]
Hi

Thank you for contacting us. We are busy testing our updated version that will be released soon, if you have any more questions, or would like to be a beta tester, please contact us via our support email - support@payfast.co.za

**Comment by ajcollett** [comment]
Thanks Brandon, I'll do that. I hope it comes out soon, I'm not sure if the way I've added a composer file has made it compatible or not.
