### ISSUE TITLE
Error log enabled

### ISSUE THREAD

**Issue by mohammedTBB** [PayFast/mod-magento_2#10]
Hi, 

There is an error showing in the checkout when the "Enable Payfast Debug Log" is set to Yes.

Exception #0 (Exception): Warning: fopen(/var/www/html/ecommerc/magento/app/code/Payfast/Payfast/Model/payfast.log): Failed to open stream: Permission denied in /var/www/html/ecommerc/magento/app/code/Payfast/Payfast/Model/payfast_common.inc on line 93

Is there any solution for this error?
Should not the log be created in the directory var/log?

**Comment by bruce-atkinson** [comment]
Hi @mohammedTBB,

This is resolved in v2.5.0 https://github.com/Payfast/mod-magento_2/pull/11.

**Comment by mohammedTBB** [comment]
Hi @appinlet,

Thanks.
