### ISSUE TITLE
Error compatibility with Magento 2.4.7 (php 8.3)

### ISSUE THREAD

**Issue by mohammedTBB** [PayFast/mod-magento_2#12]
Hi,

I have encountered a compatibility issue with Magento 2.4.7 (php 8.3).
There is an error showing in the /checkout/cart page:

1 exception(s):
Exception #0 (Exception): Deprecated Functionality: Creation of dynamic property Payfast\Payfast\Model\Config::$_storeManager is deprecated in /var/www/html/magento/app/code/Payfast/Payfast/Model/Config.php on line 87

Possible solution:
- add define the property before the constructor

```
diff --git a/app/code/Payfast/Payfast/Model/Config.php b/app/code/Payfast/Payfast/Model/Config.php
index d0fe55f20c..91c2b34649 100644
--- a/app/code/Payfast/Payfast/Model/Config.php
+++ b/app/code/Payfast/Payfast/Model/Config.php
@@ -63,6 +63,8 @@ class Config extends AbstractConfig
      */
     protected $_assetRepo;
 
+    protected $_storeManager;
+
     /**
      * @param ScopeConfigInterface $scopeConfig
      * @param Data $directoryHelper


```

**Comment by bruce-atkinson** [comment]
Hi @mohammedTBB 

Many thanks, https://github.com/Payfast/mod-magento_2/pull/13 v2.5.1 reoslves this issue.
