### ISSUE TITLE
Not receiving order confirmation and invoice emails

### ISSUE THREAD

**Issue by niralipandey** [PayFast/mod-magento_2#3]
We are not receiving the order confirmation and invoice email after order is placed and when IPN complete creating invoice also. Receiving the email when using other payment methods. Can you please help me in letting us know what is wrong or what needs to be added to receive the same.

Thank You

**Comment by Brendon-P** [comment]
Hi

Please can you submit a ticket to support@payfast.co.za and one of our dev team will follow up.

Thank you.
The PayFast team

**Comment by niralipandey** [comment]
We have resolved the issue in our code. But you are missing the email send part in code which needs to be integrated when IPN triggered and payment is confirmed

Thank You

**Comment by wikusv** [comment]
@niralipandey any chance you can share how you fixed the issue ?
